import type { AstroUserConfig } from 'astro';
import { NON_DOCS_REDIRECTS } from './src/data/redirects.ts';
import { BLOG_CATEGORIES } from './src/data/blog/categories.ts';
import deviceLibraryRedirects from './scripts/device-library-redirects.json' with { type: 'json' };
import docsRedirects from './public/redirects.json' with { type: 'json' };

// ---------------------------------------------------------------------------
// Redirect authoring policy
// ---------------------------------------------------------------------------
// This file is a thin adapter that feeds Astro's config `redirects:` — it does
// NOT own the source of truth. All editable rules live in:
//
//   - src/data/redirects.ts                         ← /docs/* + non-docs
//   - scripts/device-library-redirects.json         ← auto-generated per-platform
//
// Generated artefacts (regenerated by `pnpm generate:redirects`):
//
//   - public/_redirects      ← Cloudflare Pages format (real 301s at the edge)
//   - public/redirects.json  ← flat map consumed by THIS file for dev-mode parity
//
// Workflow:
//   1. Edit src/data/redirects.ts.
//   2. Run `pnpm generate:redirects`.
//   3. Commit both the data change and the regenerated public/_redirects +
//      public/redirects.json.
//
// Why feed redirects.json back into Astro here:
//   In static build mode, Astro.redirect()-style stubs (whether in page files
//   or via this config map) emit a 200+<meta refresh> HTML — Cloudflare's
//   _redirects file produces real 301s at the edge. Both coexist: the edge
//   rule always fires first on Cloudflare Pages. The reason we still declare
//   /docs/* rules here is so `pnpm dev` and `pnpm preview` resolve old URLs
//   locally instead of 404-ing.
//
// Cloudflare Pages reference (re: precedence):
//   "Redirects are always followed, regardless of whether or not an asset
//   matches the incoming request."
//   https://developers.cloudflare.com/pages/configuration/redirects/

// Dev-mode-only fallback. In prod, DYNAMIC_REDIRECTS in src/data/redirects.ts
// already cover these URL spaces via splat/placeholder rules at the Cloudflare
// edge. We enumerate the finite shapes here to keep `pnpm dev` / `pnpm preview`
// from 404-ing, without bloating public/_redirects with duplicate static rules.
const INDUSTRY_SLUGS = [
	'agriculture',
	'industry40',
	'smart-buildings',
	'smart-city',
	'smart-energy',
	'telecom',
	'warehouse-monitoring',
];

const devFallback: Record<string, string> = {
	'/docs/gw/search/': '/docs/iot-gateway/search/',
	'/docs/license/search/': '/docs/license-server/search/',
};
for (const slug of INDUSTRY_SLUGS) {
	devFallback[`/industries/${slug}/`] = `/clients-feedback/?category=${slug}`;
}
for (const cat of BLOG_CATEGORIES) {
	devFallback[`/blog/category/${cat}/`] = `/blog/?category=${cat}`;
	for (let page = 2; page <= 5; page++) {
		devFallback[`/blog/category/${cat}/page/${page}/`] = `/blog/?category=${cat}`;
	}
}
for (let page = 2; page <= 11; page++) {
	devFallback[`/blog/page/${page}/`] = `/blog/?page=${page}`;
}

export const redirects: AstroUserConfig['redirects'] = {
	...docsRedirects,
	...deviceLibraryRedirects,
	...NON_DOCS_REDIRECTS,
	...devFallback,
};
