/**
 * Generates redirect output files from src/data/redirects.ts:
 *   - public/_redirects      (Cloudflare Pages / Netlify format)
 *   - public/redirects.json  (flat JSON map for Node.js middleware)
 *
 * Layout produced in public/_redirects:
 *
 *   <manual header>
 *   # === Auto-generated redirects from src/data/redirects.ts ===
 *   <auto-generated static rules>
 *   # === End auto-generated redirects ===
 *   # === Dynamic redirects ===
 *   <auto-generated splat / placeholder rules>
 *
 * All dynamic rules live in the tail block because Cloudflare Pages caps the
 * first 100 entries from the first dynamic rule — any static rules past that
 * cap are silently ignored. Keeping statics on top and dynamics at the tail
 * leaves the static zone uncapped (2000-rule max).
 *
 * Refs: https://developers.cloudflare.com/pages/configuration/redirects/
 *
 * Usage: pnpm generate:redirects
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
	CATCH_ALL_REDIRECTS,
	SINGLE_REDIRECTS,
	DYNAMIC_REDIRECTS,
	getAllRedirectsFlat,
} from '../src/data/redirects.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// Helpers for PREFIX_RENAME groups with empty entries
// ---------------------------------------------------------------------------

/**
 * For PREFIX_RENAME groups with empty entries (content-enumerated by .astro files),
 * map old prefix → new prefix so we can scan the content directory and populate
 * redirects.json with individual entries.
 */
const PREFIX_RENAME_MAP: Record<string, string> = {
	'user-guide/rule-engine-2-0/nodes': 'reference/rule-engine/nodes',
	'pe/user-guide/rule-engine-2-0/nodes': 'pe/reference/rule-engine/nodes',
	'paas/user-guide/rule-engine-2-0/nodes': 'paas/reference/rule-engine/nodes',
	'paas/eu/user-guide/rule-engine-2-0/nodes': 'paas/eu/reference/rule-engine/nodes',
	'pe/solution-templates': 'pe/recipes/solution-templates',
	'paas/solution-templates': 'paas/recipes/solution-templates',
	'paas/eu/solution-templates': 'paas/eu/recipes/solution-templates',
	'iot-gateway/install': 'iot-gateway/installation',
};

/** Recursively find all .mdx files under a directory, returning relative paths without extension. */
function findMdxSlugs(dir: string, base: string = ''): string[] {
	const slugs: string[] = [];
	try {
		for (const entry of readdirSync(dir)) {
			const fullPath = join(dir, entry);
			const relPath = base ? `${base}/${entry}` : entry;
			if (statSync(fullPath).isDirectory()) {
				slugs.push(...findMdxSlugs(fullPath, relPath));
			} else if (entry.endsWith('.mdx')) {
				const slug = relPath.replace(/\.mdx$/, '').replace(/\/index$/, '');
				slugs.push(slug);
			}
		}
	} catch {
		// Directory doesn't exist
	}
	return slugs;
}

// ---------------------------------------------------------------------------
// 1. Generate public/redirects.json
// ---------------------------------------------------------------------------

const flatMap = getAllRedirectsFlat();

// Add entries for PREFIX_RENAME groups with empty entries by scanning content
for (const [oldPrefix, newPrefix] of Object.entries(PREFIX_RENAME_MAP)) {
	const contentDir = resolve(ROOT, 'src/content/docs/docs', newPrefix);
	const slugs = findMdxSlugs(contentDir);
	for (const slug of slugs) {
		flatMap[`/docs/${oldPrefix}/${slug}/`] = `/docs/${newPrefix}/${slug}/`;
	}
}
const jsonPath = resolve(ROOT, 'public/redirects.json');
writeFileSync(jsonPath, JSON.stringify(flatMap, null, 2) + '\n');

const jsonCount = Object.keys(flatMap).length;
console.log(`✓ public/redirects.json — ${jsonCount} entries`);

// ---------------------------------------------------------------------------
// 2. Generate public/_redirects
// ---------------------------------------------------------------------------

const redirectsPath = resolve(ROOT, 'public/_redirects');

const STATIC_START = '# === Auto-generated redirects from src/data/redirects.ts ===';
const STATIC_END = '# === End auto-generated redirects ===';
const DYN_START = '# === Dynamic redirects ===';

// Read existing file and preserve manually-authored rules above the auto-generated section.
const existing = readFileSync(redirectsPath, 'utf-8');
const staticStartIdx = existing.indexOf(STATIC_START);
const manualHeader = (staticStartIdx >= 0 ? existing.slice(0, staticStartIdx) : existing).trimEnd();

// ---------------------------------------------------------------------------
// Build static and dynamic output blocks
// ---------------------------------------------------------------------------

const staticLines: string[] = [];
const autoDynamicGroups: { comment?: string; rules: string[] }[] = [];

// Bucket SINGLE_REDIRECTS so single-page overrides render in the static block.
// (Catch-all groups whose entries collapse into a splat are purely dynamic — any
// specific override for that prefix still belongs in the static zone so it wins
// by being earlier in the file.)
const catchAllPrefixes = CATCH_ALL_REDIRECTS.map((g) => g.oldPrefix);
const singlesByPrefix = new Map<string, typeof SINGLE_REDIRECTS>();
const remainingSingles: typeof SINGLE_REDIRECTS = [];

for (const entry of SINGLE_REDIRECTS) {
	const matched = catchAllPrefixes.find((p) => entry.oldPath.startsWith(p + '/'));
	if (matched) {
		if (!singlesByPrefix.has(matched)) singlesByPrefix.set(matched, []);
		singlesByPrefix.get(matched)!.push(entry);
	} else {
		remainingSingles.push(entry);
	}
}

for (const group of CATCH_ALL_REDIRECTS) {
	// Single-page overrides always render statically (specific paths, not patterns).
	const overrides = singlesByPrefix.get(group.oldPrefix);
	if (overrides?.length) {
		for (const entry of overrides) {
			staticLines.push(`/docs/${entry.oldPath}/ ${entry.target} 301`);
		}
	}

	// Empty-entry PREFIX_RENAME group — one splat rule drives the whole tree.
	if (group.entries.length === 0) {
		const newPrefix = PREFIX_RENAME_MAP[group.oldPrefix];
		if (newPrefix) {
			autoDynamicGroups.push({
				rules: [`/docs/${group.oldPrefix}/* /docs/${newPrefix}/:splat 301`],
			});
		}
		continue;
	}

	// CONSOLIDATE — every entry points at the same target.
	const targets = new Set(group.entries.map((e) => e.target));
	if (targets.size === 1) {
		const target = group.entries[0].target;
		autoDynamicGroups.push({
			rules: [`/docs/${group.oldPrefix}/* ${target} 301`],
		});
		continue;
	}

	// PREFIX_RENAME with explicit entries — detect a common prefix for a splat.
	const firstEntry = group.entries[0];
	const newFull = firstEntry.target.replace(/^\/docs\//, '').replace(/\/$/, '');
	const newPrefix = newFull.slice(0, newFull.length - firstEntry.slug.length).replace(/\/$/, '');
	const allMatch = group.entries.every((e) => e.target === `/docs/${newPrefix}/${e.slug}/`);

	if (allMatch && newPrefix) {
		autoDynamicGroups.push({
			rules: [`/docs/${group.oldPrefix}/* /docs/${newPrefix}/:splat 301`],
		});
	} else {
		// Mixed targets — fall back to enumerated static rules.
		staticLines.push(`# ${group.oldPrefix} (mixed targets)`);
		for (const entry of group.entries) {
			const oldPath = entry.slug
				? `/docs/${group.oldPrefix}/${entry.slug}/`
				: `/docs/${group.oldPrefix}/`;
			staticLines.push(`${oldPath} ${entry.target} 301`);
		}
	}
}

if (remainingSingles.length > 0) {
	staticLines.push('');
	staticLines.push('# Single page redirects');
	for (const entry of remainingSingles) {
		staticLines.push(`/docs/${entry.oldPath}/ ${entry.target} 301`);
	}
}

// DYNAMIC_REDIRECTS from redirects.ts render first in the Dynamic block so
// hand-authored patterns (blog, edge upgrade) stay at the top. Group comments
// live in the data file for maintainers; the generated file stays terse.
const manualDynamicRules = DYNAMIC_REDIRECTS.flatMap((group) =>
	group.entries.map((e) => `${e.source} ${e.target} ${e.status ?? 301}`),
);

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

const dynamicHeader = [
	DYN_START,
	'# Must live AFTER all static rules: Cloudflare Pages starts a 100-rule',
	'# cap at the first dynamic rule, and any static rules past the cap are',
	'# silently ignored. Keeping dynamics here leaves the static zone uncapped.',
	'# Refs: https://developers.cloudflare.com/pages/configuration/redirects/',
];

// One flat block: manual rules first (blog, edge upgrade), then auto-derived
// splat rules. Rules are self-describing so no comments are emitted.
const autoDynamicRules = autoDynamicGroups.flatMap((g) => g.rules);
const dynamicRules = [...manualDynamicRules, ...autoDynamicRules];

const output =
	manualHeader +
	'\n\n' +
	STATIC_START +
	'\n\n' +
	staticLines.join('\n') +
	'\n\n' +
	STATIC_END +
	'\n\n' +
	dynamicHeader.join('\n') +
	'\n\n' +
	dynamicRules.join('\n') +
	'\n';

writeFileSync(redirectsPath, output);

// Count rules directly from the written file so the report matches reality
// (includes manually-authored rules from the preserved header).
let staticRuleCount = 0;
let dynamicRuleCount = 0;
for (const line of output.split('\n')) {
	const trimmed = line.trim();
	if (!trimmed || trimmed.startsWith('#')) continue;
	const src = trimmed.split(/\s+/)[0] ?? '';
	if (src.includes('*') || /:[A-Za-z_]/.test(src)) dynamicRuleCount++;
	else staticRuleCount++;
}
console.log(
	`✓ public/_redirects — ${staticRuleCount} static + ${dynamicRuleCount} dynamic (${staticRuleCount + dynamicRuleCount} total)`,
);
