// Generated by scripts/sync-edge-releases.ts — do not edit by hand, re-run the script.
// Release dates: GitHub releases of thingsboard/thingsboard-edge.
// Upgrade paths: tb-updates edge-update-v2.json, limited to released versions.

export interface EdgeRelease {
	/** Full version, e.g. "4.3.0" for the `v4.3` tag */
	version: string;
	/** GitHub release tag */
	tag: string;
	/** Publication date, YYYY-MM-DD */
	date: string;
}

/** All Edge releases, newest first. */
export const EDGE_RELEASES: EdgeRelease[] = [
	{ version: '4.4.0', tag: 'v4.4', date: '2026-10-10' },
	{ version: '4.3.1.6', tag: 'v4.3.1.6', date: '2026-10-01' },
	{ version: '4.3.1.5', tag: 'v4.3.1.5', date: '2026-10-01' },
	{ version: '4.3.1.4', tag: 'v4.3.1.4', date: '2026-08-27' },
	{ version: '4.3.1.3', tag: 'v4.3.1.3', date: '2026-07-03' },
	{ version: '4.3.1.2', tag: 'v4.3.1.2', date: '2026-06-03' },
	{ version: '4.3.1.1', tag: 'v4.3.1.1', date: '2026-04-01' },
	{ version: '4.3.1', tag: 'v4.3.1', date: '2026-03-10' },
	{ version: '4.3.0.1', tag: 'v4.3.0.1', date: '2026-02-06' },
	{ version: '4.3.0', tag: 'v4.3', date: '2026-01-21' },
	{ version: '4.2.2.6', tag: 'v4.2.2.6', date: '2026-10-01' },
	{ version: '4.2.2.5', tag: 'v4.2.2.5', date: '2026-10-01' },
	{ version: '4.2.2.4', tag: 'v4.2.2.4', date: '2026-08-27' },
	{ version: '4.2.2.3', tag: 'v4.2.2.3', date: '2026-07-03' },
	{ version: '4.2.2.2', tag: 'v4.2.2.2', date: '2026-06-03' },
	{ version: '4.2.2.1', tag: 'v4.2.2.1', date: '2026-04-01' },
	{ version: '4.2.2', tag: 'v4.2.2', date: '2026-03-10' },
	{ version: '4.2.1.2', tag: 'v4.2.1.2', date: '2026-02-06' },
	{ version: '4.2.1.1', tag: 'v4.2.1.1', date: '2026-01-21' },
	{ version: '4.2.1', tag: 'v4.2.1', date: '2026-01-21' },
	{ version: '4.2.0', tag: 'v4.2', date: '2025-09-02' },
	{ version: '4.1.0', tag: 'v4.1', date: '2025-07-23' },
	{ version: '4.0.1', tag: 'v4.0.1', date: '2025-05-15' },
	{ version: '3.9.1', tag: 'v3.9.1', date: '2025-03-14' },
	{ version: '3.9.0', tag: 'v3.9', date: '2025-01-13' },
	{ version: '3.8.0', tag: 'v3.8', date: '2024-10-11' },
	{ version: '3.7.0', tag: 'v3.7', date: '2024-06-18' },
	{ version: '3.6.4', tag: 'v3.6.4', date: '2024-04-11' },
	{ version: '3.6.3', tag: 'v3.6.3', date: '2024-03-18' },
	{ version: '3.6.2', tag: 'v3.6.2', date: '2023-12-28' },
	{ version: '3.6.1', tag: 'v3.6.1', date: '2023-11-15' },
	{ version: '3.6.0', tag: 'v3.6', date: '2023-09-21' },
	{ version: '3.5.1.1', tag: 'v3.5.1.1', date: '2023-07-04' },
	{ version: '3.5.1', tag: 'v3.5.1', date: '2023-06-01' },
	{ version: '3.5.0', tag: 'v3.5', date: '2023-05-10' },
	{ version: '3.4.3', tag: 'v3.4.3', date: '2022-12-22' },
	{ version: '3.4.1', tag: 'v3.4.1', date: '2022-08-19' },
	{ version: '3.4.0', tag: 'v3.4', date: '2022-07-26' },
	{ version: '3.3.4.1', tag: 'v3.3.4.1', date: '2022-04-29' },
	{ version: '3.3.4', tag: 'v3.3.4', date: '2022-03-23' },
];

/** Direct upgrade paths: version → versions it upgrades to, and whether the database upgrade runs. */
export const EDGE_UPGRADE_GRAPH: Record<string, { to: string; db: boolean }[]> = {
	'4.3.1.6': [{ to: '4.4.0', db: true }],
	'4.3.1.5': [{ to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.1.4': [{ to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.1.3': [{ to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.1.2': [{ to: '4.3.1.3', db: false }, { to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.1.1': [{ to: '4.3.1.2', db: false }, { to: '4.3.1.3', db: false }, { to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.1': [{ to: '4.3.1.1', db: false }, { to: '4.3.1.2', db: false }, { to: '4.3.1.3', db: false }, { to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.0.1': [{ to: '4.3.1', db: false }, { to: '4.3.1.1', db: false }, { to: '4.3.1.2', db: false }, { to: '4.3.1.3', db: false }, { to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.3.0': [{ to: '4.3.0.1', db: false }, { to: '4.3.1', db: false }, { to: '4.3.1.1', db: false }, { to: '4.3.1.2', db: false }, { to: '4.3.1.3', db: false }, { to: '4.3.1.4', db: false }, { to: '4.3.1.5', db: false }, { to: '4.3.1.6', db: false }, { to: '4.4.0', db: true }],
	'4.2.2.6': [{ to: '4.3.1.6', db: true }],
	'4.2.2.5': [{ to: '4.2.2.6', db: false }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.2.4': [{ to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.2.3': [{ to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.2.2': [{ to: '4.2.2.3', db: false }, { to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.1.2', db: true }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.2.1': [{ to: '4.2.2.2', db: false }, { to: '4.2.2.3', db: false }, { to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.1.1', db: true }, { to: '4.3.1.2', db: true }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.2': [{ to: '4.2.2.1', db: false }, { to: '4.2.2.2', db: false }, { to: '4.2.2.3', db: false }, { to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.1', db: true }, { to: '4.3.1.1', db: true }, { to: '4.3.1.2', db: true }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.1.2': [{ to: '4.2.2', db: false }, { to: '4.2.2.1', db: false }, { to: '4.2.2.2', db: false }, { to: '4.2.2.3', db: false }, { to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.0', db: true }, { to: '4.3.0.1', db: true }, { to: '4.3.1', db: true }, { to: '4.3.1.1', db: true }, { to: '4.3.1.2', db: true }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.1.1': [{ to: '4.2.1.2', db: false }, { to: '4.2.2', db: false }, { to: '4.2.2.1', db: false }, { to: '4.2.2.2', db: false }, { to: '4.2.2.3', db: false }, { to: '4.2.2.4', db: false }, { to: '4.2.2.5', db: false }, { to: '4.2.2.6', db: false }, { to: '4.3.0', db: true }, { to: '4.3.0.1', db: true }, { to: '4.3.1', db: true }, { to: '4.3.1.1', db: true }, { to: '4.3.1.2', db: true }, { to: '4.3.1.3', db: true }, { to: '4.3.1.4', db: true }, { to: '4.3.1.5', db: true }, { to: '4.3.1.6', db: true }],
	'4.2.1': [{ to: '4.2.1.1', db: false }, { to: '4.2.1.2', db: false }],
	'4.2.0': [{ to: '4.2.1.2', db: true }],
	'4.1.0': [{ to: '4.2.0', db: true }],
	'4.0.1': [{ to: '4.1.0', db: true }],
	'3.9.1': [{ to: '4.0.1', db: true }],
	'3.9.0': [{ to: '3.9.1', db: true }],
	'3.8.0': [{ to: '3.9.0', db: true }],
	'3.7.0': [{ to: '3.8.0', db: true }],
	'3.6.4': [{ to: '3.7.0', db: true }],
	'3.6.3': [{ to: '3.6.4', db: true }],
	'3.6.2': [{ to: '3.6.4', db: true }],
	'3.6.1': [{ to: '3.6.2', db: true }],
	'3.6.0': [{ to: '3.6.1', db: true }],
};
